/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simoncherry_findface_util_JNIUtils */

#ifndef _Included_com_simoncherry_findface_util_JNIUtils
#define _Included_com_simoncherry_findface_util_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simoncherry_findface_util_JNIUtils
 * Method:    doGrayScale
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_simoncherry_findface_util_JNIUtils_doGrayScale
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_simoncherry_findface_util_JNIUtils
 * Method:    doEdgeDetection
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_simoncherry_findface_util_JNIUtils_doEdgeDetection
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_simoncherry_findface_util_JNIUtils
 * Method:    doBinaryzation
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_simoncherry_findface_util_JNIUtils_doBinaryzation
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_simoncherry_findface_util_JNIUtils
 * Method:    setClassifier
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_simoncherry_findface_util_JNIUtils_setClassifier
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_simoncherry_findface_util_JNIUtils
 * Method:    deleteCassifier
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_simoncherry_findface_util_JNIUtils_deleteCassifier
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_simoncherry_findface_util_JNIUtils
 * Method:    detectFace
 * Signature: ([III)[Lcom/simoncherry/findface/model/CVFace;
 */
JNIEXPORT jobjectArray JNICALL Java_com_simoncherry_findface_util_JNIUtils_detectFace
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
